mp.metrics.tags.app=temperatura-converter-jee
otel.service.name=temperatura-converter-jee
otel.exporter.otlp.endpoint=http://otel-collector:4318
otel.exporter.otlp.protocol=http/protobuf
# ponytail: desativa tracing se collector off, evita timeout startup
mp.telemetry.enabled=false
